# Generated by Django 2.0.3 on 2018-06-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='isTA',
            field=models.BooleanField(default=False),
        ),
    ]
