# Generated by Django 2.0.3 on 2018-06-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='department',
            field=models.CharField(choices=[('CS', '컴퓨터공학과'), ('GL', '글로컬IT학과'), ('SW', '소프트웨어공학과'), ('JT', '정보통신공학과'), ('IT', 'IT자율융합학부'), ('etc', '기타')], default='etc', max_length=3),
        ),
    ]
