# Generated by Django 2.0.3 on 2018-06-11 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_baseuser_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='isTA',
        ),
    ]
