# Generated by Django 2.0.3 on 2018-06-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_baseuser_department'),
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='students',
            field=models.ManyToManyField(to='account.Student'),
        ),
    ]
