# Generated by Django 2.0.3 on 2018-06-11 06:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_lecture_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=1000)),
                ('content_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(null=True, upload_to='')),
                ('limited_date', models.DateTimeField(null=True)),
                ('is_notice', models.BooleanField()),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.Lecture')),
            ],
        ),
    ]
