# Generated by Django 2.0.3 on 2018-06-14 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0010_auto_20180614_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectureinfo',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Student'),
        ),
    ]
